POST https://7jh42r9fj0.execute-api.eu-west-1.amazonaws.com/beta/location
Content-Type: application/json

{
    "Item":
    {
        "name": "Tokio",
        "xCoord": "-35.6584421",
        "yCoord": "139.7328635"
    }
}